"use strict";
// Public names and game rarity values; independent of the private roster.
const sleepAssets = {
    "items": {
        "Bagon Incense": "items/incense-pokemon-15.webp",
        "Bug-Type Candy M": "items/item-67.webp",
        "Bulbasaur Incense": "items/incense-pokemon-5.webp",
        "Cetoddle Incense": "items/incense-pokemon-6.webp",
        "Charmander Incense": "items/incense-pokemon-2.webp",
        "Chikorita Incense": "items/incense-pokemon-5.webp",
        "Chimchar Incense": "items/incense-pokemon-2.webp",
        "Comfey Incense": "items/incense-pokemon-18.webp",
        "Cramorant Incense": "items/incense-pokemon-10.webp",
        "Cresselia Biscuit": "items/item-99.webp",
        "Cresselia Down": "items/item-100.webp",
        "Cresselia Incense": "items/incense-pokemon-11.webp",
        "Cutiefly Incense": "items/incense-pokemon-18.webp",
        "Cyndaquil Incense": "items/incense-pokemon-2.webp",
        "Dark-Type Candy M": "items/item-71.webp",
        "Dedenne Incense": "items/incense-pokemon-4.webp",
        "Dragon-Type Candy M": "items/item-70.webp",
        "Dragon-Type Candy S": "items/item-52.webp",
        "Drampa Incense": "items/incense-pokemon-15.webp",
        "Dratini Incense": "items/incense-pokemon-15.webp",
        "Dream Cluster M": "items/item-19.webp",
        "Dream Cluster S": "items/item-18.webp",
        "Dream Coin": "items/item-107.webp",
        "Dwebble Incense": "items/incense-pokemon-12.webp",
        "E-Zzz Travel Ticket": "items/item-7.webp",
        "Eevee (Halloween) Incense": "items/incense-pokemon-1.webp",
        "Eevee (Holiday) Incense": "items/incense-pokemon-1.webp",
        "Eevee Incense": "items/incense-pokemon-1.webp",
        "Electric-Type Candy M": "items/item-59.webp",
        "Electric-Type Candy S": "items/item-41.webp",
        "Energy Pillow": "items/item-5.webp",
        "Entei Incense": "items/incense-pokemon-2.webp",
        "Expert Ticket": "items/item-104.webp",
        "Fairy-Type Candy M": "items/item-73.webp",
        "Farfetch’d Incense": "items/incense-pokemon-10.webp",
        "Fighting-Type Candy M": "items/item-62.webp",
        "Fire Stone": "items/item-22.webp",
        "Fire-Type Candy S": "items/item-39.webp",
        "Flying-Type Candy M": "items/item-65.webp",
        "Focus Incense": "items/item-1.webp",
        "Friend Incense": "items/item-34.webp",
        "Ghost-Type Candy M": "items/item-69.webp",
        "Good Camp Ticket": "items/item-8.webp",
        "Grass-Type Candy M": "items/item-60.webp",
        "Great Biscuit": "items/item-10.webp",
        "Ground-Type Candy M": "items/item-64.webp",
        "Ground-Type Candy S": "items/item-46.webp",
        "Growth Incense": "items/item-3.webp",
        "Grubbin Incense": "items/incense-pokemon-12.webp",
        "Handy Candy L": "items/item-14.webp",
        "Handy Candy M": "items/item-13.webp",
        "Handy Candy S": "items/item-12.webp",
        "Happiny Incense": "items/incense-pokemon-1.webp",
        "Hawlucha Incense": "items/incense-pokemon-10.webp",
        "Helper Whistle": "items/item-6.webp",
        "Ice Stone": "items/item-26.webp",
        "Ingredient Ticket M": "items/item-16.webp",
        "Ingredient Ticket S": "items/item-15.webp",
        "Larvitar Incense": "items/incense-pokemon-13.webp",
        "Latias Biscuit": "items/item-110.webp",
        "Latias Down": "items/item-111.webp",
        "Latias Incense": "items/incense-pokemon-15.webp",
        "Latias and Latios Biscuit": "items/item-112.webp",
        "Latios Down": "items/item-113.webp",
        "Latios Incense": "items/incense-pokemon-15.webp",
        "Leaf Stone": "items/item-25.webp",
        "Linking Cord": "items/item-21.webp",
        "Luck Incense": "items/item-2.webp",
        "Main Skill Seed": "items/item-32.webp",
        "Master Biscuit": "items/item-11.webp",
        "Mawile Incense": "items/incense-pokemon-17.webp",
        "Metapod Incense": "items/incense-pokemon-12.webp",
        "Mewtwo Biscuit": "items/item-117.webp",
        "Mewtwo DNA": "items/item-118.webp",
        "Mewtwo Incense": "items/incense-pokemon-11.webp",
        "Mimikyu Incense": "items/incense-pokemon-14.webp",
        "Minun Incense": "items/incense-pokemon-4.webp",
        "Moon Stone": "items/item-27.webp",
        "Mudkip Incense": "items/incense-pokemon-3.webp",
        "Munna Incense": "items/incense-pokemon-11.webp",
        "Murkrow Incense": "items/incense-pokemon-16.webp",
        "Natu Incense": "items/incense-pokemon-11.webp",
        "Neutralizing Mint": "items/item-103.webp",
        "Noibat Incense": "items/incense-pokemon-15.webp",
        "Normal-Type Candy M": "items/item-56.webp",
        "Onix Incense": "items/incense-pokemon-13.webp",
        "Oval Stone": "items/item-30.webp",
        "Pawmi Incense": "items/incense-pokemon-4.webp",
        "Pichu Incense": "items/incense-pokemon-4.webp",
        "Pikachu (Captain) Incense": "items/incense-pokemon-4.webp",
        "Pikachu (Holiday) Incense": "items/incense-pokemon-4.webp",
        "Piplup Incense": "items/incense-pokemon-3.webp",
        "Plusle Incense": "items/incense-pokemon-4.webp",
        "Poison-Type Candy M": "items/item-63.webp",
        "Poison-Type Candy S": "items/item-45.webp",
        "Poké Biscuit": "items/item-9.webp",
        "Pokémon material": "items/item-105.webp",
        "Premier Biscuit": "items/item-106.webp",
        "Psychic-Type Candy M": "items/item-66.webp",
        "Psychic-Type Candy S": "items/item-48.webp",
        "Pumpkaboo Incense": "items/incense-pokemon-14.webp",
        "Raikou Incense": "items/incense-pokemon-4.webp",
        "Ralts Incense": "items/incense-pokemon-11.webp",
        "Recovery Incense": "items/item-4.webp",
        "Relaxing Nap Ticket": "items/item-114.webp",
        "Rock-Type Candy M": "items/item-68.webp",
        "Rufflet Incense": "items/incense-pokemon-10.webp",
        "Sandshrew Incense": "items/incense-pokemon-9.webp",
        "Shinx Incense": "items/incense-pokemon-4.webp",
        "Shiny Stone": "items/item-28.webp",
        "Shuckle Incense": "items/incense-pokemon-12.webp",
        "Slakoth Incense": "items/incense-pokemon-1.webp",
        "Spheal (Holiday) Incense": "items/incense-pokemon-6.webp",
        "Spiritomb Incense": "items/incense-pokemon-16.webp",
        "Sprigatito Incense": "items/incense-pokemon-5.webp",
        "Squirtle Incense": "items/incense-pokemon-3.webp",
        "Steel-Type Candy M": "items/item-72.webp",
        "Stufful Incense": "items/incense-pokemon-7.webp",
        "Sub Skill Seed": "items/item-33.webp",
        "Suicune Incense": "items/incense-pokemon-3.webp",
        "Sylveon Incense": "items/incense-pokemon-18.webp",
        "Thunder Stone": "items/item-24.webp",
        "Tinkatink Incense": "items/incense-pokemon-18.webp",
        "Togedemaru Incense": "items/incense-pokemon-17.webp",
        "Torchic Incense": "items/incense-pokemon-2.webp",
        "Totodile Incense": "items/incense-pokemon-3.webp",
        "Toxel Incense": "items/incense-pokemon-8.webp",
        "Trapinch Incense": "items/incense-pokemon-9.webp",
        "Treecko Incense": "items/incense-pokemon-5.webp",
        "Turtwig Incense": "items/incense-pokemon-5.webp",
        "Tyrunt Incense": "items/incense-pokemon-13.webp",
        "Ultra Biscuit": "items/item-94.webp",
        "Vulpix (Alolan Form) Incense": "items/incense-pokemon-6.webp",
        "Vulpix Incense": "items/incense-pokemon-2.webp",
        "Water Stone": "items/item-23.webp",
        "Water-Type Candy M": "items/item-58.webp",
        "Water-Type Candy S": "items/item-40.webp",
        "Wooper (Paldean Form) Incense": "items/incense-pokemon-8.webp",
        "Absol Candy": "items/candy-359.webp",
        "Aron Candy": "items/candy-304.webp",
        "Bagon Candy": "items/candy-371.webp",
        "Bellsprout Candy": "items/candy-69.webp",
        "Bulbasaur Candy": "items/candy-1.webp",
        "Caterpie Candy": "items/candy-10.webp",
        "Cetoddle Candy": "items/candy-974.webp",
        "Chansey Candy": "items/candy-113.webp",
        "Charmander Candy": "items/candy-4.webp",
        "Chikorita Candy": "items/candy-152.webp",
        "Chimchar Candy": "items/candy-390.webp",
        "Clefairy Candy": "items/candy-35.webp",
        "Comfey Candy": "items/candy-764.webp",
        "Cramorant Candy": "items/candy-845.webp",
        "Cresselia Candy": "items/candy-488.webp",
        "Croagunk Candy": "items/candy-453.webp",
        "Cubone Candy": "items/candy-104.webp",
        "Cutiefly Candy": "items/candy-742.webp",
        "Cyndaquil Candy": "items/candy-155.webp",
        "Darkrai Candy": "items/candy-491.webp",
        "Dedenne Candy": "items/candy-702.webp",
        "Delibird Candy": "items/candy-225.webp",
        "Diglett Candy": "items/candy-50.webp",
        "Ditto Candy": "items/candy-132.webp",
        "Doduo Candy": "items/candy-84.webp",
        "Drampa Candy": "items/candy-780.webp",
        "Dratini Candy": "items/candy-147.webp",
        "Drifloon Candy": "items/candy-425.webp",
        "Dwebble Candy": "items/candy-557.webp",
        "Eevee Candy": "items/candy-133.webp",
        "Ekans Candy": "items/candy-23.webp",
        "Entei Candy": "items/candy-244.webp",
        "Farfetch’d Candy": "items/candy-83.webp",
        "Fuecoco Candy": "items/candy-909.webp",
        "Gastly Candy": "items/candy-92.webp",
        "Geodude Candy": "items/candy-74.webp",
        "Growlithe Candy": "items/candy-58.webp",
        "Grubbin Candy": "items/candy-736.webp",
        "Gulpin Candy": "items/candy-316.webp",
        "Hawlucha Candy": "items/candy-701.webp",
        "Heracross Candy": "items/candy-214.webp",
        "Houndour Candy": "items/candy-228.webp",
        "Jigglypuff Candy": "items/candy-39.webp",
        "Kangaskhan Candy": "items/candy-115.webp",
        "Larvitar Candy": "items/candy-246.webp",
        "Latias Candy": "items/candy-380.webp",
        "Latios Candy": "items/candy-381.webp",
        "Lucario Candy": "items/candy-448.webp",
        "Magnemite Candy": "items/candy-81.webp",
        "Mankey Candy": "items/candy-56.webp",
        "Mareep Candy": "items/candy-179.webp",
        "Mawile Candy": "items/candy-303.webp",
        "Meowth Candy": "items/candy-52.webp",
        "Mew Candy": "items/candy-151.webp",
        "Mewtwo Candy": "items/candy-150.webp",
        "Mimikyu Candy": "items/candy-778.webp",
        "Minun Candy": "items/candy-312.webp",
        "Mr. Mime Candy": "items/candy-122.webp",
        "Mudkip Candy": "items/candy-258.webp",
        "Munna Candy": "items/candy-517.webp",
        "Murkrow Candy": "items/candy-198.webp",
        "Natu Candy": "items/candy-177.webp",
        "Noibat Candy": "items/candy-714.webp",
        "Onix Candy": "items/candy-95.webp",
        "Pawmi Candy": "items/candy-921.webp",
        "Pikachu Candy": "items/candy-25.webp",
        "Pinsir Candy": "items/candy-127.webp",
        "Piplup Candy": "items/candy-393.webp",
        "Plusle Candy": "items/candy-311.webp",
        "Psyduck Candy": "items/candy-54.webp",
        "Pumpkaboo Candy": "items/candy-710.webp",
        "Quaxly Candy": "items/candy-912.webp",
        "Raikou Candy": "items/candy-243.webp",
        "Ralts Candy": "items/candy-280.webp",
        "Rattata Candy": "items/candy-19.webp",
        "Rufflet Candy": "items/candy-627.webp",
        "Sableye Candy": "items/candy-302.webp",
        "Sandshrew Candy": "items/candy-27.webp",
        "Shinx Candy": "items/candy-403.webp",
        "Shuckle Candy": "items/candy-213.webp",
        "Shuppet Candy": "items/candy-353.webp",
        "Slakoth Candy": "items/candy-287.webp",
        "Slowpoke Candy": "items/candy-79.webp",
        "Sneasel Candy": "items/candy-215.webp",
        "Snover Candy": "items/candy-459.webp",
        "Spheal Candy": "items/candy-363.webp",
        "Spiritomb Candy": "items/candy-442.webp",
        "Sprigatito Candy": "items/candy-906.webp",
        "Squirtle Candy": "items/candy-7.webp",
        "Stufful Candy": "items/candy-759.webp",
        "Sudowoodo Candy": "items/candy-185.webp",
        "Suicune Candy": "items/candy-245.webp",
        "Swablu Candy": "items/candy-333.webp",
        "Tinkatink Candy": "items/candy-957.webp",
        "Togedemaru Candy": "items/candy-777.webp",
        "Togepi Candy": "items/candy-175.webp",
        "Torchic Candy": "items/candy-255.webp",
        "Totodile Candy": "items/candy-158.webp",
        "Toxel Candy": "items/candy-848.webp",
        "Trapinch Candy": "items/candy-328.webp",
        "Treecko Candy": "items/candy-252.webp",
        "Turtwig Candy": "items/candy-387.webp",
        "Tyrunt Candy": "items/candy-696.webp",
        "Vulpix Candy": "items/candy-37.webp",
        "Wobbuffet Candy": "items/candy-202.webp",
        "Wooper Candy": "items/candy-194.webp",
        "Dream Shards": "items/dream-shards.webp"
},
    "ingredients": {
        "Bean Sausage": "ingredients/sausage.png",
        "Fancy Apple": "ingredients/apple.png",
        "Fancy Egg": "ingredients/egg.png",
        "Fiery Herb": "ingredients/herb.png",
        "Glossy Avocado": "ingredients/avocado.png",
        "Greengrass Corn": "ingredients/corn.png",
        "Greengrass Soybeans": "ingredients/soybean.png",
        "Honey": "ingredients/honey.png",
        "Large Leek": "ingredients/leek.png",
        "Moomoo Milk": "ingredients/milk.png",
        "Plump Pumpkin": "ingredients/pumpkin.png",
        "Pure Oil": "ingredients/oil.png",
        "Rousing Coffee": "ingredients/coffee.png",
        "Slowpoke Tail": "ingredients/tail.png",
        "Snoozy Tomato": "ingredients/tomato.png",
        "Soft Potato": "ingredients/potato.png",
        "Soothing Cacao": "ingredients/cacao.png",
        "Tasty Mushroom": "ingredients/mushroom.png",
        "Warming Ginger": "ingredients/ginger.png"
    },
    "berries": {
        "Belue Berry": "berries/belue.png",
        "Bluk Berry": "berries/bluk.png",
        "Cheri Berry": "berries/cheri.png",
        "Chesto Berry": "berries/chesto.png",
        "Durin Berry": "berries/durin.png",
        "Figy Berry": "berries/figy.png",
        "Grepa Berry": "berries/grepa.png",
        "Leppa Berry": "berries/leppa.png",
        "Lum Berry": "berries/lum.png",
        "Mago Berry": "berries/mago.png",
        "Oran Berry": "berries/oran.png",
        "Pamtre Berry": "berries/pamtre.png",
        "Pecha Berry": "berries/pecha.png",
        "Persim Berry": "berries/persim.png",
        "Rawst Berry": "berries/rawst.png",
        "Sitrus Berry": "berries/sitrus.png",
        "Wiki Berry": "berries/wiki.png",
        "Yache Berry": "berries/yache.png"
    },
    "specialties": {
        "Berries": "badges/berry.png",
        "Ingredients": "badges/ingredient.png",
        "Skills": "badges/strength.png"
    },
    "subskills": {
        "Sleep EXP Bonus": "gold",
        "Helping Bonus": "gold",
        "Energy Recovery Bonus": "gold",
        "Dream Shard Bonus": "gold",
        "Research EXP Bonus": "gold",
        "Helping Speed S": "normal",
        "Helping Speed M": "silver",
        "Berry Finding S": "gold",
        "Inventory Up S": "normal",
        "Inventory Up M": "silver",
        "Skill Level Up S": "silver",
        "Ingredient Finder S": "normal",
        "Ingredient Finder M": "silver",
        "Skill Trigger S": "normal",
        "Skill Trigger M": "silver",
        "Skill Level Up M": "gold",
        "Inventory Up L": "silver"
    }
};

// Legendary species metadata from PokéAPI; Mythical is a separate classification.
// https://github.com/PokeAPI/pokeapi/blob/master/data/v2/csv/pokemon_species.csv
const legendarySpecies = new Set([144, 145, 146, 150, 243, 244, 245, 249, 250, 377, 378, 379, 380, 381, 382, 383, 384, 480, 481, 482, 483, 484, 485, 486, 487, 488, 638, 639, 640, 641, 642, 643, 644, 645, 646, 716, 717, 718, 772, 773, 785, 786, 787, 788, 789, 790, 791, 792, 800, 888, 889, 890, 891, 892, 894, 895, 896, 897, 898, 905, 1001, 1002, 1003, 1004, 1007, 1008, 1014, 1015, 1016, 1017, 1024]);

const subskillAbbreviations = {
    "Skill Trigger S": "STS",
    "Skill Trigger M": "STM",
    "Helping Speed S": "HSS",
    "Helping Speed M": "HSM",
    "Helping Bonus": "HB",
    "Berry Finding S": "BFS",
    "Ingredient Finder S": "IFS",
    "Ingredient Finder M": "IFM",
    "Inventory Up S": "IUS",
    "Inventory Up M": "IUM",
    "Inventory Up L": "IUL",
    "Skill Level Up S": "SLUS",
    "Skill Level Up M": "SLUM",
    "Sleep EXP Bonus": "SEB",
    "Research EXP Bonus": "REB",
    "Dream Shard Bonus": "DSB",
    "Energy Recovery Bonus": "ERB"
};
