const assert=require('node:assert/strict');
const islands=require('../pokemon-sleep/island-settings.js');
const engine=require('../pokemon-sleep/analyzer/engine.js');
const outcomes=require('../pokemon-sleep/analyzer/outcomes.js');
const data=require('../pokemon-sleep/analyzer/data.json');
const snapshot=require('../pokemon-sleep/snapshots/2026-10-04-1c3647d40662.json');
assert.equal(islands.favorite('powerplant','Grepa Berry'),true);
assert.equal(islands.favorite('cyan','Grepa Berry'),false);
assert.equal(islands.favorite('greengrass','Grepa Berry'),null);
assert.equal(islands.savedBonus('snowdrop',snapshot.inventory),43);
assert.equal(islands.savedBonus('amber',snapshot.inventory),62);
assert.equal(islands.savedBonus('cyan',{island_bests:[]}),null);
assert.equal(islands.savedBonus('cyan',{island_bests:[{name:'Cyan Beach',area_bonus_percent:0}]}),0);
assert.equal(islands.savedBonus('cyan',{island_bests:[{name:'Cyan Beach',area_bonus_percent:'85'}]}),null);
assert.match(islands.note('cyan',snapshot.inventory,42),/overridden/);
assert.match(islands.note('cyan',null,0),/not recorded/);
const build=engine.fromRoster(data,snapshot.roster.records.find(m=>m.id==='mon-50'));
const result=engine.simulate(build,engine.defaultConditions);
const base=outcomes.evaluate(build,result,{});
const favored=outcomes.evaluate(build,result,{areaBonus:85,favoriteBerry:true});
assert.equal(favored.berryStrength,base.berryStrength*2*1.85);
assert.equal(favored.skillStrength,base.skillStrength*1.85);
const shardBuild=engine.fromRoster(data,snapshot.roster.records.find(m=>m.id==='mon-17'));
const shardResult=engine.simulate(shardBuild,engine.defaultConditions);
assert.equal(outcomes.evaluate(shardBuild,shardResult,{areaBonus:85,favoriteBerry:true}).dreamShards,outcomes.evaluate(shardBuild,shardResult,{}).dreamShards);
console.log('Island favorites, dated bonuses, missing versus zero, strength scaling and unchanged shard rewards verified.');
