const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const context=await browser.newContext({viewport:{width:1440,height:1100}});
 const page=await context.newPage(); const errors=[],tracking=[];
 page.on('pageerror',e=>errors.push(e.message)); page.on('request',r=>{if(/google-analytics|googletagmanager/.test(r.url()))tracking.push(r.url());});
 const origin=process.env.SLEEP_TEST_ORIGIN||'http://localhost:8769';
 await page.goto(origin+'/pokemon-sleep/?analytics=off');
 await page.waitForSelector('#grid .card');
 await page.getByRole('button',{name:/View charge king,/}).click();
 await page.waitForSelector('#detail .detail-production-card');
 assert.equal(await page.locator('#detail .detail-production-card').count(),3);
 const detailValues=await page.locator('#detail .detail-production-card strong').allTextContents();
 const helperUrl=new URL(await page.getByRole('link',{name:'Analyze this helper →'}).getAttribute('href'),origin);
 await page.getByRole('link',{name:'Analyze this helper →'}).click();
 await page.waitForSelector('#results:not([hidden])');
 assert.equal(await page.locator('#saved').inputValue(),helperUrl.searchParams.get('pokemon'));
 assert.equal(await page.locator('#species').inputValue(),'AMPHAROS');
 assert.deepEqual(await page.locator('#production-cards strong').allTextContents(),detailValues);
 assert.match(await page.locator('#saved-note').innerText(),/Carry limit and ribbon/);
 const original=await page.locator('#production-cards').innerText();
 await page.getByRole('button',{name:'Keep as comparison'}).click();
 await page.locator('#energy').selectOption('high');
 assert.notEqual(await page.locator('#production-cards').innerText(),original);
 assert.equal(await page.locator('#comparison').isVisible(),true);
 await page.locator('#level').fill('60'); await page.locator('#level').blur();
 await page.waitForTimeout(300);
 await page.locator('#subskill-0').selectOption('Helping Speed M');
 await page.locator('#subskill-1').selectOption('Helping Speed M');
 assert.match(await page.locator('#calculation-status').innerText(),/only once/);
 assert.equal(await page.locator('#results').isVisible(),false);
 await page.getByRole('button',{name:'Reset build'}).click();
 assert.equal(await page.locator('#results').isVisible(),true);
 await page.locator('#species').selectOption('BLASTOISE');
 await page.locator('#level').fill('60'); await page.locator('#level').blur(); await page.waitForTimeout(300);
 await page.locator('#nature').selectOption('Modest');
 await page.locator('#skill-level').fill('7');
 await page.locator('#area').fill('50');
 await page.locator('#favorite-berry').check();
 await page.locator('#carry').fill('27'); await page.locator('#carry').blur();
 await page.locator('#energy').selectOption('high');
 await page.locator('#collect').selectOption('6');
 await page.locator('#sleep').fill('9'); await page.locator('#sleep').blur();
 await page.locator('#bonus').selectOption('2'); await page.locator('#ribbon').selectOption('2000');
 await page.locator('#camp').check();
 await page.locator('#ingredient-1').selectOption('1');
 await page.locator('#subskill-0').selectOption('Skill Trigger S');
 await page.locator('#subskill-1').selectOption('Helping Speed M');
 await page.waitForTimeout(300);
 await page.evaluate(()=>scrollTo(0,0));
 await page.screenshot({path:'/tmp/sleep-analyzer-desktop.png',fullPage:true});
 // Force clipboard fallback, then reload the generated build URL.
 await page.evaluate(()=>{Object.defineProperty(navigator,'clipboard',{value:{writeText:async()=>{throw Error('unavailable')}}});});
 const before=await page.locator('#production-cards').innerText();
 await page.getByRole('button',{name:'Copy build link'}).click();
 await page.reload(); await page.waitForSelector('#results:not([hidden])');
 assert.equal(await page.locator('#species').inputValue(),'BLASTOISE');
 assert.equal(await page.locator('#level').inputValue(),'60');
 assert.equal(await page.locator('#nature').inputValue(),'Modest');
 assert.equal(await page.locator('#skill-level').inputValue(),'7');
 assert.equal(await page.locator('#area').inputValue(),'50');
 assert.equal(await page.locator('#favorite-berry').isChecked(),true);
 assert.equal(await page.locator('#carry').inputValue(),'27');
 assert.equal(await page.locator('#camp').isChecked(),true);
 assert.equal(await page.locator('#sleep').inputValue(),'9');
 assert.equal(await page.locator('#collect').inputValue(),'6');
 assert.equal(await page.locator('#energy').inputValue(),'high');
 assert.equal(await page.locator('#bonus').inputValue(),'2');
 assert.equal(await page.locator('#ribbon').inputValue(),'2000');
 assert.equal(await page.locator('#ingredient-1').inputValue(),'1');
 assert.equal(await page.locator('#subskill-0').inputValue(),'Skill Trigger S');
 assert.equal(await page.locator('#production-cards').innerText(),before);
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/tmp/sleep-analyzer-mobile.png',fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
 await page.goto(origin+'/pokemon-sleep/analyzer/?snapshot=missing&pokemon=mon-1&analytics=off');
 await page.waitForSelector('#results:not([hidden])');
 assert.equal(await page.locator('#saved').inputValue(),'','unavailable snapshot must not resolve snapshot-local IDs against latest');
 assert.match(await page.locator('#load-status').innerText(),/snapshot could not be loaded/);
 const collection=await (await context.request.get(origin+'/pokemon-sleep/roster.json')).json();
 const costume=collection.records.find(m=>m.variant==='Costume');
 if(costume){ await page.locator('#saved').selectOption(costume.id); assert.equal(await page.locator('#results').isVisible(),false); }
 // A missing roster must not prevent independent custom analysis.
 await page.route('**/pokemon-sleep/roster.json',route=>route.fulfill({status:503,body:'Unavailable'}));
 await page.goto(origin+'/pokemon-sleep/analyzer/?analytics=off');
 await page.waitForSelector('#results:not([hidden])');
 assert.match(await page.locator('#load-status').innerText(),/Custom builds still work/);
 assert.deepEqual(errors,[]); assert.deepEqual(tracking,[]);
 console.log('Browser verified: helper → analyzer, build changes, comparison, duplicate validation, reset, shared build reload, mobile layout, no page errors or analytics requests.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
